# Generated by Django 5.2.4 on 2025-08-02 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
